<a href="https://colab.research.google.com/github/robitussin/CCADMACL_EXERCISES/blob/main/Exercise8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 8

In [1]:
!pip install pyECLAT

Requirement already satisfied: pyECLAT in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (1.0.2)
Requirement already satisfied: pandas>=0.25.3 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pyECLAT) (1.26.4)
Requirement already satisfied: tqdm>=4.41.1 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pyECLAT) (4.66.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pandas>=0.25.3->pyECLAT) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pandas>=0.25.3->pyECLAT) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from pandas>=0.25.3->pyECLAT) (2023.3)
Requirement already satisfied: colorama in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from tqdm>=4.41.1->pyECLAT) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\carla\miniconda3\envs\com222ml\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.16.0)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\carla\miniconda3\envs\COM222ML\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\carla\miniconda3\envs\COM222ML\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\carla\miniconda3\envs\COM222ML\Lib\site-packages)

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning, module="seaborn")
warnings.filterwarnings("ignore", category=Warning)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

from pyECLAT import ECLAT

In [ ]:
url = "https://github.com/robitussin/CCADMACL_EXERCISES/blob/8fdec5cd3f29586f9934e035187c7f16da382361/pc_games_market_basket.csv?raw=true"
# url = "pc_games_market_basket.csv"

df = pd.read_csv(url, header=None)
# df = pd.read_csv(url, header=None)
df.head()

,0,1,2,3,4,5
0,No Man's Sky,Left 4 Dead 2,Elden Ring,GTA V,Monster Hunter: World,NaN
1,Red Dead Redemption 2,Counter-Strike 2,Left 4 Dead 2,NaN,NaN,NaN
2,No Man's Sky,Monster Hunter: World,NaN,NaN,NaN,NaN
3,Elden Ring,Divinity: Original Sin 2,Monster Hunter: World,Factorio,Sekiro: Shadows Die Twice,Wolfenstein II
4,Rainbow Six Siege,Doom Eternal,Dark Souls 3,Cyberpunk 2077,BioShock Infinite,NaN

### 1. Generate transaction lists from the dataset

In [4]:
txns = df.fillna("").values.tolist()
txns = [[item for item in txn if item != ''] for txn in txns]
txns = [[item.strip() for item in txn] for txn in txns]

# Create a list of unique ids for the transactions
ids = [i + 1 for i in range(len(txns))]

# Initialize an empty list
data =[]
# Iterate through transactions and add them to the DataFrame with IDs
for i, txn in enumerate(txns):
    data.extend([{'TID': ids[i], 'Item': item} for item in txn])

df_txn = pd.DataFrame(data)
df_txn.head(25)

    TID                       Item
0     1               No Man's Sky
1     1              Left 4 Dead 2
2     1                 Elden Ring
3     1                      GTA V
4     1      Monster Hunter: World
5     2      Red Dead Redemption 2
6     2           Counter-Strike 2
7     2              Left 4 Dead 2
8     3               No Man's Sky
9     3      Monster Hunter: World
10    4                 Elden Ring
11    4   Divinity: Original Sin 2
12    4      Monster Hunter: World
13    4                   Factorio
14    4  Sekiro: Shadows Die Twice
15    4             Wolfenstein II
16    5          Rainbow Six Siege
17    5               Doom Eternal
18    5               Dark Souls 3
19    5             Cyberpunk 2077
20    5          BioShock Infinite
21    6            Baldur's Gate 3
22    6   Divinity: Original Sin 2
23    7              Left 4 Dead 2
24    7            Resident Evil 4

### 2. Find the most frequent items

In [5]:
# Find the top 30 most frequent items
top_items = df_txn['Item'].value_counts().reset_index()

# Convert the top 30 items into DataFrame and sort by item count in descending order
df_top_items = pd.DataFrame(top_items)
df_top_items.columns = ['Item', 'Count']

# Calculate the percentage of transactions for each item
total_transactions = len(df)
df_top_items['% Count'] = (df_top_items['Count']*100 / total_transactions).round(2)

# Display the results
df_top_items.style.background_gradient(cmap='Blues')

3. Generate frequent itemsets using ECLAT

In [6]:

# Initiate an Eclat instance and load transactions DataFrame to the instance
eclat = ECLAT(data=df, verbose=True)

# Generate a binary dataframe
eclat.df_bin.head()

100%|██████████| 74/74 [00:00<00:00, 371.18it/s]
100%|██████████| 74/74 [00:00<00:00, 4695.16it/s]
100%|██████████| 74/74 [00:00<00:00, 2062.73it/s]

,Stardew Valley,Cyberpunk 2077,Red Dead Redemption 2,Slay the Spire,The Forest,L.A. Noire,Stardew Valley,Cities: Skylines,Skyrim,Doom Eternal,Celeste,Quake Champions,Counter-Strike 2,Elden Ring,BioShock Infinite,Baldur's Gate 3,Subnautica,Rainbow Six Siege,RimWorld,Factorio,Slay the Spire,Cities: Skylines,Skyrim,Portal 2,Fallout 4,Portal 2,The Witcher 3,Counter-Strike 2,The Witcher 3,Hades,Monster Hunter: World,Half-Life 2,Wolfenstein II,Call of Duty: Modern Warfare 2,RimWorld,Monster Hunter: World,Cyberpunk 2077,Call of Duty: Modern Warfare 2,Dead Cells,Baldur's Gate 3,L.A. Noire,Hades,Divinity: Original Sin 2,Left 4 Dead 2,Divinity: Original Sin 2,Red Dead Redemption 2,No Man's Sky,Rainbow Six Siege,Dead Cells,Wolfenstein II,Sekiro: Shadows Die Twice,Hollow Knight,Half-Life 2,Hollow Knight,GTA V,Terraria,BioShock Infinite,Fallout 4,Subnautica,GTA V,Terraria,Doom Eternal,Sekiro: Shadows Die Twice,Dark Souls 3,Quake Champions,Elden Ring,Left 4 Dead 2,Resident Evil 4,Factorio,Resident Evil 4,The Forest,No Man's Sky,Celeste,Dark Souls 3
0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0

In [7]:
unique_item_list = eclat.uniq_
print(unique_item_list)

[' Stardew Valley', ' Cyberpunk 2077', 'Red Dead Redemption 2', ' Slay the Spire', 'The Forest', 'L.A. Noire', 'Stardew Valley', 'Cities: Skylines', 'Skyrim', 'Doom Eternal', 'Celeste', 'Quake Champions', ' Counter-Strike 2', ' Elden Ring', ' BioShock Infinite', " Baldur's Gate 3", 'Subnautica', 'Rainbow Six Siege', 'RimWorld', ' Factorio', 'Slay the Spire', ' Cities: Skylines', ' Skyrim', 'Portal 2', 'Fallout 4', ' Portal 2', ' The Witcher 3', 'Counter-Strike 2', 'The Witcher 3', 'Hades', ' Monster Hunter: World', ' Half-Life 2', 'Wolfenstein II', ' Call of Duty: Modern Warfare 2', ' RimWorld', 'Monster Hunter: World', 'Cyberpunk 2077', 'Call of Duty: Modern Warfare 2', 'Dead Cells', "Baldur's Gate 3", ' L.A. Noire', ' Hades', ' Divinity: Original Sin 2', ' Left 4 Dead 2', nan, 'Divinity: Original Sin 2', ' Red Dead Redemption 2', " No Man's Sky", ' Rainbow Six Siege', ' Dead Cells', ' Wolfenstein II', ' Sekiro: Shadows Die Twice', ' Hollow Knight', 'Half-Life 2', 'Hollow Knight', 'GTA V', 'Terraria', 'BioShock Infinite', ' Fallout 4', ' Subnautica', ' GTA V', ' Terraria', ' Doom Eternal', 'Sekiro: Shadows Die Twice', ' Dark Souls 3', ' Quake Champions', 'Elden Ring', 'Left 4 Dead 2', ' Resident Evil 4', 'Factorio', 'Resident Evil 4', ' The Forest', "No Man's Sky", ' Celeste', 'Dark Souls 3']

4. Show itemsets and support values

In [8]:
min_support_threshold = 0.0065
min_combination = 2
max_combination = 2

get_ECLAT_indexes, get_ECLAT_supports = eclat.fit(min_support = min_support_threshold, min_combination = min_combination, max_combination = max_combination, separator=' & ', verbose=True)

# Display results in a dataframe
result = pd.DataFrame(get_ECLAT_supports.items(),columns=['Item', 'Support'])
result = result.sort_values(by=['Support'], ascending=False).reset_index(drop=True)
result

Combination 2 by 2

2701it [00:35, 76.42it/s]

                                         Item  Support
0                         Hades &  The Forest   0.0104
1     Sekiro: Shadows Die Twice &  The Forest   0.0100
2                            Hades &  Celeste   0.0090
3                       GTA V &  Doom Eternal   0.0088
4                      Elden Ring &  Terraria   0.0088
..                                        ...      ...
180            Rainbow Six Siege &  Fallout 4   0.0066
181               Wolfenstein II &  Fallout 4   0.0066
182                        Skyrim &  Terraria   0.0066
183   Sekiro: Shadows Die Twice &  Subnautica   0.0066
184      Monster Hunter: World &  Half-Life 2   0.0066

[185 rows x 2 columns]